### ISSUE TITLE
Catch timeouts

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-demo-cleanup#11]
The script atm is showing timeout when trying to ascertain the usage of user with complex data (not necessarily large, but, say, many images with attachments and KVPs on them).

Expected behaviour:
Let the script always finish, skip the user with complex data maybe using ``try... catch`` (= a basic feature request), but, possibly, report about such user at the end output (=a nice to have feature).

@will-moore 

```
omero demo-cleanup --force --gigabytes 100
....
Finding disk usage of "user-with-complex-data" (#5828).
Traceback (most recent call last):
  File "/opt/omero/server/venv3/bin/omero", line 8, in <module>
    sys.exit(main())
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/main.py", line 126, in main
    rv = omero.cli.argv()
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/cli.py", line 1787, in argv
    cli.invoke(args[1:])
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/cli.py", line 1225, in invoke
    stop = self.onecmd(line, previous_args)
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/cli.py", line 1302, in onecmd
    self.execute(line, previous_args)
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/cli.py", line 1384, in execute
    args.func(args)
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero_demo_cleanup/cli.py", line 53, in _wrapper
    return func(self, *args, **kwargs)
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero_demo_cleanup/cli.py", line 133, in cleanup
    self.gateway, minimum_days=args.days, ignore_users=ignore
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero_demo_cleanup/library.py", line 322, in resource_usage
    rsp = submit(conn, DiskUsage2(targetObjects=user), DiskUsage2Response)
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero_demo_cleanup/library.py", line 118, in submit
    cb = conn.c.submit(request, loops=500)
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/clients.py", line 988, in submit
    closehandle=True)
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/clients.py", line 1007, in waitOnCmd
    callback.loop(loops, ms)  # Throw LockTimeout
  File "/opt/omero/server/venv3/lib64/python3.6/site-packages/omero/callbacks.py", line 265, in loop
    5000, int(waited))
omero.LockTimeout: exception ::omero::LockTimeout
{
    serverStackTrace = None
    serverExceptionClass = None
    message = Command unfinished after 250.0 seconds
    backOff = 5000
    seconds = 250
}
```

**Comment by joshmoore** [comment]
https://github.com/ome/omero-demo-cleanup/blob/main/src/omero_demo_cleanup/library.py#L118 can either (1) be updated to use a longer value or (2) have arguments added (like [`--wait`](https://github.com/ome/omero-py/blob/master/src/omero/cli.py#L941)) to let the user configure this time.
